kind: ConfigMap
apiVersion: v1
metadata:
  name: hello-service
  labels:
    karaf.pid: com.iws.hello
data:
  broker: tcp://broker-amq-tcp:61616
  username: user
  password: password
  brokerTopic: jms:queue:hello.requests
  publishedEndpointUrl: http://localhost:8181/sayHello
  
